/*
 * This source file was generated by the Gradle 'init' task
 */
package projet;

import java.util.Scanner;

import projet.Class.Character.Aventurer;
import projet.Menu.Menu;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Aventurer player = Menu.initPlayer(scanner);
        boolean inGame = true;

        Menu.mainMenu(inGame, player, scanner);
    }
}
